---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
  namespace: app-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: ${ECR_CLIENT_REPOSITORY}:latest
          imagePullPolicy: Always
          env:
          - name: GRPC_SERVER_HOST
            value: "grpc-server.app-grpc"
          - name: GRPC_SERVER_PORT
            value: "9000"
      restartPolicy: Always